Company.PL/Controllers/EmployeeController.cs
using AutoMapper;
using Company.BLL.Interfaces;
using Company.DAL.Models;
using Company.PL.Dtos;
using Company.PL.Helpers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Company.PL.Controllers
{
    [Authorize]
    public class EmployeeController : Controller
    {
        //private readonly IEmployeeRepository _employeeRepository;
        //private readonly IDepartmentRepository _departmentRepository;
        private readonly IMapper _mapper;
        private readonly IUnitOfWork _unitOfWork;

        public EmployeeController
            (
            //IEmployeeRepository employeeRepository,
            //IDepartmentRepository departmentRepository,
            IMapper mapper,
            IUnitOfWork unitOfWork
            )
        {
            //_employeeRepository = employeeRepository;
            //_departmentRepository = departmentRepository;
            _mapper = mapper;
            _unitOfWork = unitOfWork;
        }
        public async Task<IActionResult> Index(string? SearchInput)
        {
            IEnumerable<Employee> employees;

            if (string.IsNullOrEmpty(SearchInput))
                employees = await _unitOfWork.EmployeeRepository.GetAllAsync();
            else
                employees = await _unitOfWork.EmployeeRepository.GetByNameAsync(SearchInput);
            //// Dictionary : 3 Properties
            //// 1.ViewData : Transfer Data from Controller (Action) to View
            //ViewData["Message"] = "Hello From ViewData!";

            //// 2.ViewBag  : Transfer Data from Controller (Action) to View
            //ViewBag.Message = new { Message = "Hello From ViewBag!" };

            // 3.TempData 

            return View(employees);
        }

        public IActionResult Create()
        {
            //var departments = _departmentRepository.GetAll();
            //ViewBag.Departments = departments;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateEmployeeDto model)
        {
            if (ModelState.IsValid)
            {
                if (model.Image is not null)
                    model.ImageName = FileSettings.UploadFile(model.Image, "images");

                var employee = _mapper.Map<Employee>(model);
                await _unitOfWork.EmployeeRepository.AddAsync(employee);

                var count = await _unitOfWork.CompleteAsync();
                if (count > 0)
                {

                    TempData["Message"] = "Employee Added Successfully!";

                    return RedirectToAction("Index");
                }
            }

            return View(model);
        }

        public async Task<IActionResult> Details(int? id, string viewName = "Details")
        {
            //var departments = _departmentRepository.GetAll();
            //ViewBag.Departments = departments;
            if (id is null)
                return BadRequest("Invalid Id");
            var employee = await _unitOfWork.EmployeeRepository.GetAsync(id.Value);
            if (employee is null)
                return NotFound(new { statusCode = 404, message = $"Employee with id {id} Not Found" });

            var dto = _mapper.Map<CreateEmployeeDto>(employee);
            return View(viewName, dto);
        }

        public Task<IActionResult> Edit(int? id)
        {
            return Details(id, "Edit");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] int id, CreateEmployeeDto model)
        {
            if (ModelState.IsValid)
            {

                if (id != model.Id)
                    return BadRequest("Invalid Id");

                if (model.ImageName is not null && model.Image is not null)
                    FileSettings.DeleteFile(model.ImageName, "images");

                if (model.Image is not null)
                    model.ImageName = FileSettings.UploadFile(model.Image, "images");


                var employee = _mapper.Map<Employee>(model);
                _unitOfWork.EmployeeRepository.Update(employee);
                var count = await _unitOfWork.CompleteAsync();
                if (count > 0)
                    return RedirectToAction("Index");
            }


            return View(model);
        }

        public Task<IActionResult> Delete(int? id)
        {
            return Details(id, "Delete");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete([FromRoute] int id, CreateEmployeeDto model)
        {
            if (id != model.Id)
                return BadRequest("Invalid Id");

            var employee = _mapper.Map<Employee>(model);
            _unitOfWork.EmployeeRepository.Delete(employee);
            var count = await _unitOfWork.CompleteAsync();

            if (count > 0)
            {
                if (model.ImageName is not null)
                    FileSettings.DeleteFile(model.ImageName, "images");

                return RedirectToAction("Index");
            }
            return View(model);
        }
    }
}

Company.PL/Controllers/RoleController.cs
using Company.DAL.Models;
using Company.PL.Dtos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Company.PL.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<AppUser> _userManager;

        public RoleController(RoleManager<IdentityRole> roleManager, UserManager<AppUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index(string? SearchInput)
        {
            IEnumerable<RoleToReturnDTO> roles;
            if (string.IsNullOrEmpty(SearchInput))
            {
                roles = _roleManager.Roles.Select(r => new RoleToReturnDTO()
                {
                    Id = r.Id,
                    Name = r.Name
                });
            }
            else
            {
                roles = _roleManager.Roles.Select(r => new RoleToReturnDTO()
                {
                    Id = r.Id,
                    Name = r.Name
                }).Where(r => r.Name.ToLower().Contains(SearchInput.ToLower()));
            }

            return View(roles);
        }

        public IActionResult Search(string SearchInput)
        {
            var roles = _roleManager.Roles
                .Where(r => r.Name.ToLower().Contains(SearchInput.ToLower()))
                .Select(r => new RoleToReturnDTO
                {
                    Id = r.Id,
                    Name = r.Name
                });
            return PartialView("PartialViews/_RoleTablePartialView", roles);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(RoleToReturnDTO model)
        {
            if (ModelState.IsValid)
            {
                var roleResult = await _roleManager.FindByNameAsync(model.Name);
                if (roleResult is not null)
                    ModelState.AddModelError("", "Role already exists");

                var role = new IdentityRole()
                {
                    Name = model.Name
                };

                var result = await _roleManager.CreateAsync(role);
                if (result.Succeeded)
                {
                    TempData["Message"] = "Role Created Successfully!";
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError("", "Invalid Operation");
            }
            return View(model);
        }

        public async Task<IActionResult> Details(string? id, string viewName = "Details")
        {
            if (id == null)
                return BadRequest("Invalid Id");

            var role = await _roleManager.FindByIdAsync(id);

            if (role == null)
                return NotFound(new { statusCode = 404, message = $"Role with id {id} was not found" });

            var roleToReturn = new RoleToReturnDTO()
            {
                Id = role.Id,
                Name = role.Name
            };

            return View(viewName, roleToReturn);
        }

        public async Task<IActionResult> Edit(string? id)
        {
            return await Details(id, "Edit");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] string id, RoleToReturnDTO model)
        {
            if (ModelState.IsValid)
            {
                if (id != model.Id)
                    return BadRequest("Invalid Operation");

                var role = await _roleManager.FindByIdAsync(id);
                if (role is null)
                    return NotFound(new { statusCode = 404, message = $"Role with id {id} was not found" });

                var roleResult = await _roleManager.FindByNameAsync(model.Name);
                if (roleResult is not null)
                    ModelState.AddModelError("", "Role already exists");


                role.Name = model.Name;

                var result = await _roleManager.UpdateAsync(role);
                if (result.Succeeded)
                {
                    TempData["Message"] = "Role Updated Successfully!";
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError("", "Invalid Operation");
            }
            return View(model);
        }

        public async Task<IActionResult> Delete(string? id)
        {
            return await Details(id, "Delete");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(string id, RoleToReturnDTO model)
        {
            if (ModelState.IsValid)
            {
                if (id != model.Id)
                    return BadRequest("Invalid Operation");

                var role = await _roleManager.FindByIdAsync(id);

                if (role is null)
                    return NotFound(new { statusCode = 404, message = $"Role with id {id} was not found" });

                var result = await _roleManager.DeleteAsync(role);
                if (result.Succeeded)
                {
                    TempData["Message"] = "Role Deleted Successfully!";
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError("", "Invalid Operation");
            }
            return View(model);
        }

        public async Task<IActionResult> AddOrRemoveUsers(string roleId)
        {
            var role = await _roleManager.FindByIdAsync(roleId);
            if (role is null)
                return NotFound(new { statusCode = 404, message = $"Role with id {roleId} was not found" });

            ViewData["RoleId"] = roleId;

            var usersInRole = new List<UsersInRoleDTO>();
            var users = await _userManager.Users.ToListAsync();
            foreach (var user in users)
            {
                usersInRole.Add(new UsersInRoleDTO()
                {
                    UserId = user.Id,
                    UserName = user.UserName,
                    IsSelected = await _userManager.IsInRoleAsync(user, role.Name)
                });
            }

            return View(usersInRole);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrRemoveUsers(string roleId, List<UsersInRoleDTO> users)
        {
            var role = await _roleManager.FindByIdAsync(roleId);
            if (role is null)
                return NotFound(new { statusCode = 404, message = $"Role with id {roleId} was not found" });

            if (ModelState.IsValid)
            {
                foreach (var user in users)
                {
                    var appUser = _userManager.FindByIdAsync(user.UserId).Result;
                    if (appUser is not null)
                    {
                        if (user.IsSelected && !await _userManager.IsInRoleAsync(appUser, role.Name))
                        {
                            await _userManager.AddToRoleAsync(appUser, role.Name);
                        }
                        else if (!user.IsSelected && await _userManager.IsInRoleAsync(appUser, role.Name))
                        {
                            await _userManager.RemoveFromRoleAsync(appUser, role.Name);

                        }

                    }

                }
                TempData["Message"] = "Users Updated Successfully!";
                return RedirectToAction("Edit", new { id = roleId });
            }
            return View(users);
        }
    }
}

Company.PL/Controllers/UserController.cs
using Company.DAL.Models;
using Company.PL.Dtos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Company.PL.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        private readonly UserManager<AppUser> _userManager;

        public UserController(UserManager<AppUser> userManager)
        {
            _userManager = userManager;
        }
        public IActionResult Index(string? SearchInput)
        {
            IEnumerable<UserToReturnDTO> users;
            if (string.IsNullOrEmpty(SearchInput))
            {
                users = _userManager.Users.Select(u => new UserToReturnDTO()
                {
                    Id = u.Id,
                    UserName = u.UserName,
                    FirstName = u.FirstName,
                    LastName = u.LastName,
                    Email = u.Email,
                    Roles = _userManager.GetRolesAsync(u).Result
                });
            }
            else
            {
                users = _userManager.Users.Select(u => new UserToReturnDTO()
                {
                    Id = u.Id,
                    UserName = u.UserName,
                    FirstName = u.FirstName,
                    LastName = u.LastName,
                    Email = u.Email,
                    Roles = _userManager.GetRolesAsync(u).Result
                }).Where(u => u.FirstName.ToLower().Contains(SearchInput.ToLower()));
            }

            return View(users);
        }

        public async Task<IActionResult> Details(string? id, string viewName = "Details")
        {
            if (id == null)
                return BadRequest("Invalid Id");

            var user = await _userManager.FindByIdAsync(id);

            if (user == null)
                return NotFound(new { statusCode = 404, message = $"User with id {id} was not found" });

            var userToReturn = new UserToReturnDTO()
            {
                Id = user.Id,
                UserName = user.UserName,
                FirstName = user.FirstName,
                LastName = user.LastName,
                Email = user.Email,
                Roles = _userManager.GetRolesAsync(user).Result
            };

            return View(viewName, userToReturn);
        }

        public async Task<IActionResult> Edit(string? id)
        {
            return await Details(id, "Edit");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] string id, UserToReturnDTO model)
        {
            if (ModelState.IsValid)
            {
                if (id != model.Id)
                    return BadRequest("Invalid Operation");

                var user = await _userManager.FindByIdAsync(id);

                if (user == null)
                    return NotFound(new { statusCode = 404, message = $"User with id {id} was not found" });

                user.UserName = model.UserName;
                user.FirstName = model.FirstName;
                user.LastName = model.LastName;
                user.Email = model.Email;

                var result = await _userManager.UpdateAsync(user);
                if (result.Succeeded)
                {
                    TempData["Message"] = "User Updated Successfully!";
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError("", "Invalid Operation");
            }
            return View(model);
        }

        public async Task<IActionResult> Delete(string? id)
        {
            return await Details(id, "Delete");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(string id, UserToReturnDTO model)
        {
            if (ModelState.IsValid)
            {
                if (id != model.Id)
                    return BadRequest("Invalid Operation");

                var user = await _userManager.FindByIdAsync(id);

                if (user == null)
                    return NotFound(new { statusCode = 404, message = $"User with id {id} was not found" });

                var result = await _userManager.DeleteAsync(user);
                if (result.Succeeded)
                {
                    TempData["Message"] = "User Deleted Successfully!";
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError("", "Invalid Operation");
            }
            return View(model);
        }

    }
}

Company.PL/Views/Shared/_AuthLayout.cshtml
<!--
Author: Colorlib
Author URL: https://colorlib.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
	<title>Creative Colorlib SignUp Form</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<!-- Custom Theme files -->
	<link href="~/css/authLayout.css" rel="stylesheet" type="text/css" media="all" />
	<!-- //Custom Theme files -->
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<!-- //web font -->
</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">

		<h1>Creative @ViewData["Title"] Form</h1>


		@RenderBody()



		<!-- copyright -->
		<div class="colorlibcopy-agile">
			<p>© 2018 Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a></p>
		</div>


		<!-- //copyright -->
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->

	<script src="~/lib/jquery/dist/jquery.min.js"></script>

	@await RenderSectionAsync("ValidationScriptSection", required: false)

</body>
</html>

Company.PL/Views/Shared/_ButtonsPartialView.cshtml
@model string

<td>
    <a class="btn btn-info" asp-action="Details" asp-route-id="@Model">Details</a>
</td>
<td>
    <a class="btn btn-warning" asp-action="Edit" asp-route-id="@Model">Update</a>
</td>
<td>
    <a class="btn btn-danger" asp-action="Delete" asp-route-id="@Model">Delete</a>
</td>

Company.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Company.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Company.PL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Company.PL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn btn-danger text-white" asp-controller="Account" asp-action="SignOut">Sign Out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Company.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>